### ISSUE TITLE
[question] - cgroupfs-mount on alpine?

### ISSUE THREAD

**Issue by MichelDiz** [tianon/cgroupfs-mount#12]
Is possible to install cgroupfs-mount on alpine?

Related issue https://github.com/rancher/k3s/issues/1387

Cheers.

**Comment by tianon** [comment]
On Alpine I'd suggest setting `rc_cgroup_mode` to either `hybrid` or `legacy` and using the `/etc/init.d/cgroups` service to mount these instead.

If you're determined, it should be pretty trivial to download the `cgroupfs-mount` script (it's self-contained) and run it on your Alpine system (it's even `#!/bin/sh` so you shouldn't need to install `bash` for it to work).

**Comment by MichelDiz** [comment]
Thank you for your answer, I'm analyzing and trying troubleshooting this.

When you sai, "download the cgroupfs-mount" you mean download this repo or download the release? Reading the docker file, feels like I'll have more steps to do.

Cheers.

**Comment by tianon** [comment]
I mean literally the shell script: https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount

(It's a pretty short, simple shell script, and it's really the only meaningful thing in this entire repository -- everything else is just packaging/support structure.)

**Comment by MichelDiz** [comment]
Thank you Tianon, you were very kind in paying attention to my issue. Unfortunately, I tried, but it didn't work. Either my limitations prevented me or it is something beyond me.

Thanks again!

Cheers!
