### ISSUE TITLE
Project appears to be unlicensed

### ISSUE THREAD

**Issue by saltedcoffii** [tianon/cgroupfs-mount#19]
This source code doesn't have a license, as far as I can tell. According to https://choosealicense.com/no-permission/, a project without a license is "all rights reserved" and prohibits users from compiling/distributing binaries of this software. Please add a license. There is a relatively exhaustive list at https://choosealicense.com/appendix. Also, by adding a license this (depending on the license) allows third parties such as unix-like distributions to package this software and distribute binaries. Thank you for your consideration!
DISCLAIMER: I'm not a laywer, this isn't legal advice.

**Comment by tianon** [comment]
I suppose a `LICENSE` file at the top level would probably make sense, but this was created specifically for Debian (as a so called "native package"), so the license information is in `debian/copyright`:

https://github.com/tianon/cgroupfs-mount/blob/0549428171605eae3097a3e21bf7664845eac9e8/debian/copyright#L6-L9

(GPL-3+)

**Comment by tianon** [comment]
Fixed in https://github.com/tianon/cgroupfs-mount/commit/ebe05307c7f2a0e78aa3a1e52aad7059ead0e13b, thanks!
