### ISSUE TITLE
Please add installation/usage instructions

### ISSUE THREAD

**Issue by fogshot** [tianon/cgroupfs-mount#5]
I'm trying to get docker running on my Server running Ubuntu 14.04 and your package was mentioned as a possible solution to [this problem](http://stackoverflow.com/questions/32002882/error-starting-docker-daemon-on-ubuntu-14-04-devices-cgroup-isnt-mounted).

However, I have no idea how to best install your package, could you elaborate in the README.md?

**Comment by tianon** [comment]
Thanks for the suggestion!
