### ISSUE TITLE
mount: permission denied on debian (raspbian jessie)

### ISSUE THREAD

**Issue by jayproulx** [tianon/cgroupfs-mount#8]
I'm setting up a Docker image for AWS Greengrass, which requires cgroups directories to be mounted:
http://docs.aws.amazon.com/greengrass/latest/developerguide/gg-dg.pdf

Specifically (which actually appears to be out of date):
```
curl https://raw.githubusercontent.com/tianon/cgroupfsmount/951c38ee8d802330454bdede20d85ec1c0f8d312/cgroupfs-mount
> cgroupfs-mount.sh
chmod +x cgroupfs-mount.sh
sudo bash ./cgroupfs-mount.sh
```

In my Dockerfile, I'm using the apt-get install cgroupsfs-mount approach:
```
Step 9/15 : RUN sudo cgroupfs-mount
 ---> Running in cc187c3fb61f
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
mount: permission denied
```

I added some debug echos, since it wasn't clear where the permission denied messages where coming from:
```
Step 10/16 : RUN sudo bash /app/cgroupfs-mount.sh
 ---> Running in ced257974766
making directory cpuset
cpuset not mounted
mount: permission denied
tried to mount cpuset, but failed, removing it
making directory cpu
cpu not mounted
mount: permission denied
tried to mount cpu, but failed, removing it
making directory cpuacct
cpuacct not mounted
mount: permission denied
tried to mount cpuacct, but failed, removing it
making directory blkio
blkio not mounted
mount: permission denied
tried to mount blkio, but failed, removing it
making directory memory
memory not mounted
mount: permission denied
tried to mount memory, but failed, removing it
making directory devices
devices not mounted
mount: permission denied
tried to mount devices, but failed, removing it
making directory freezer
freezer not mounted
mount: permission denied
tried to mount freezer, but failed, removing it
making directory net_cls
net_cls not mounted
mount: permission denied
tried to mount net_cls, but failed, removing it
making directory perf_event
perf_event not mounted
mount: permission denied
tried to mount perf_event, but failed, removing it
making directory net_prio
net_prio not mounted
mount: permission denied
tried to mount net_prio, but failed, removing it
making directory hugetlb
hugetlb not mounted
mount: permission denied
tried to mount hugetlb, but failed, removing it
making directory pids
pids not mounted
mount: permission denied
tried to mount pids, but failed, removing it
```

I'm not entirely sure what's going on here, or why the mount is failing, thoughts?

**Comment by tianon** [comment]
Running these scripts inside a Docker container is very rarely ever going
to make any sense.  If you have a working Docker instance, you already have
appropriately mounted cgroups on your host, and bind-mounting those inside
a container is going to be about the only useful way I'm aware of to
actually accomplish what you're after if your application requires write
access to cgroups.

**Comment by jayproulx** [comment]
Thanks for the quick respose @tianon, to be transparent, I'm not entirely sure how cgroups works, it's a requirement of AWS Greengrass, I tried bind mounting `mount -t cgroup -o $sys,bind cgroup $sys`, but same permission denied issue.

Still trying to work through this, thanks for the insight

**Comment by tianon** [comment]
Yeah, this repository (and the scripts it contains) are _definitely_ not what you're looking for.  They're for setting up cgroups on your host.

Docker provides a read-only copy of your container's cgroups at `/sys/fs/cgroup` by default, and if you need read-write access, you have to bind-mount them yourself via `-v /sys/fs/cgroup:/sys/fs/cgroup` on `docker run`, but beware that it's dangerous to do so.

It sounds like https://github.com/lambci/docker-lambda might also be of interest to you.

**Comment by jayproulx** [comment]
Thanks @tianon, you're right, this is unnecessary, Greengrass runs successfully in my RPi Docker image without running these scripts, which is contrary to the Greengrass dependency checker which says it fails, even though all the cgroup mounts are available in the running image on the RPi.

I appreciate your responses.
